server:
  port: 8081

spring:
  application:
    name: graduacao
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${PGR_POSTGRES_HOST:localhost}:${PGR_POSTGRES_PORT:5432}/${PGR_POSTGRES_DB:tccdb}
    driver-class-name: org.postgresql.Driver
    username: ${PGR_POSTGRES_USER:tcc}
    password: ${PGR_POSTGRES_PASSWORD:tcc123}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        '[format_sql]': true
        '[default_schema]': ${PGR_DEFAULT_SCHEMA:public}
        hbm2ddl:
          '[create_namespaces]': true
    open-in-view: false

logging:
  level:
    '[org.springframework]': ${INFRA_LOG_LEVEL:INFO}
    '[org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver]': ERROR
    '[org.apache.catalina]': ${INFRA_LOG_LEVEL:INFO}
    '[org.hibernate]': ${INFRA_LOG_LEVEL:INFO}
    '[com.zaxxer.hikari]': ${INFRA_LOG_LEVEL:INFO}
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%-5level){level} %clr([%thread]){cyan} %clr(traceId=%X{traceId:-} spanId=%X{spanId:-} requestId=%X{requestId:-}){magenta} %clr(%logger{36}){blue} - %msg%n"

springdoc:
  swagger-ui:
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
