server:
  port: 8081

spring:
  application:
    name: graduacao
  datasource:
    url: jdbc:postgresql://${PGR_POSTGRES_HOST:localhost}:${PGR_POSTGRES_PORT:5432}/${PGR_POSTGRES_DB:tccdb}
    driver-class-name: org.postgresql.Driver
    username: ${PGR_POSTGRES_USER:tcc}
    password: ${PGR_POSTGRES_PASSWORD:tcc123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
        '[default_schema]': ${PGR_DEFAULT_SCHEMA:public}
        hbm2ddl:
          '[create_namespaces]': true
    open-in-view: false

logging:
  level:
    '[org.springframework.web]': INFO
