server:
  port: 8081

spring:
  application:
    name: graduacao
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:tccdb}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:tcc}
    password: ${POSTGRES_PASSWORD:tcc123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
    open-in-view: false

logging:
  level:
    '[org.springframework.web]': INFO
